spring.application.name=app

# Conexión directa a SQL Server por puerto local con usuario sa
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=petshop;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=petshop123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Petshop app properties
petshop.reset.cleaner.rate=300000

